### ISSUE TITLE
see this issue? it is an issue

### ISSUE THREAD

**Issue by smellysox1** [RasperRevision/RasperRevision.github.io#1]
![image](https://github.com/RasperRevision/RasperRevision.github.io/assets/80152017/73d97d10-6313-4a71-a624-00c970f36362)

**Comment by smellysox1** [comment]
i fix BUT 
![image](https://github.com/RasperRevision/RasperRevision.github.io/assets/80152017/75d6fde2-e90d-496a-90b7-6ea309ba0d4b)

**Comment by smellysox1** [comment]
i dunno what i did.
https://rasperrevision.github.io/favicon.ico no work now

**Comment by smellysox1** [comment]
what and where is favicon.ico?

**Comment by RasperRevision** [comment]
there is no favicon.ico
