### ISSUE TITLE
RAFAEL PLACE THE ISSUES HEREE ITS HARD TO READ!

### ISSUE THREAD

**Issue by smellysox1** [RasperRevision/RasperRevision.github.io#15]
**Brief description**
...

**To Reproduce**
...

**Expected behavior**
...

**Device information**
- OS: ...
- Browser: ...
- Version: ...
- etc

**Additional context (proposed solution, screenshots etc)**
...

**Comment by RasperRevision** [comment]
JASPER WHAT ARE YOU DOING?? WHY DOES THE HOMEPAGE KEEP BREAKING?

**Comment by RasperRevision** [comment]
STOP MAKING THINGS SPIN

**Comment by RasperRevision** [comment]
THE SITE IS UNUSABLE
